apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: app-tekton-argo
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: vote-ui
    app.kubernetes.io/name: vote-ui
    app.kubernetes.io/part-of: vote-ui
    app.openshift.io/runtime: java
  name: vote-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-ui
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
      - name: vote-ui
        imagePullPolicy: Always
        image: quay.io/sachinayyar/vote-app:latest
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5

