apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-tekton-spring-boot
  namespace: openshift-gitops
spec:
  destination:
    namespace: tekton-argocd
    server: https://api.cluster-dx2vl.dx2vl.sandbox2618.opentlc.com:6443
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/sachinayyar/opeshift-gitops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
