apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev
    server: 'https://api.cluster-t9vdh.t9vdh.sandbox2832.opentlc.com:6443'
  project: default
  source:
    path: k8s
    repoURL: 'https://github.com/sachinayyar/tekton-spring-boot-config.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
