apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-spring-boot
  namespace: openshift-gitops
  annotations:
    argocd-image-updater.argoproj.io/image-alias.force-update: 'true'
    argocd-image-updater.argoproj.io/image-alias.update-strategy: 1
spec:
  destination:
    name: ''
    namespace: tekton-argocd
    server: https://kubernetes.default.svc
  source:
    path: app
    repoURL: https://github.com/sachinayyar/opeshift-gitops.git
    targetRevision: main
  project: default
