apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: quay.io/sachinayyar/tekton-argocd
    argocd-image-updater.argoproj.io/dex.image-name: tekton-argocd
    argocd-image-updater.argoproj.io/dex.image-tag: ^1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: tekton-spring-boot
  namespace: openshift-gitops
spec:
  destination:
    namespace: tekton-argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/sachinayyar/opeshift-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


