apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-tekton-argo
  namespace: openshift-gitops
spec:
  destination:
    namespace: tekton-argo
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/sachinayyar/opeshift-gitops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
